### ISSUE TITLE
Allow specifying Redis connection parameters

### ISSUE THREAD

**Issue by justinas** [aruseni/django-qrauth#1]
As there's no way to specify connection parameters at the moment, the Redis client connects using the defaults (localhost, port 6379, and the zero-th DB).

It would be desirable to have a settings item to set these parameters (or even hand in a `Redis()` connection?) so people with different configurations could also use the app.

**Comment by aruseni** [comment]
Good point. :+1:
I think I’ll try to implement this. Thank you. :)

**Comment by aruseni** [comment]
Please try the new AUTH_QR_CODE_REDIS_KWARGS setting (see the updated README.md) inroduced in https://github.com/aruseni/django-qrauth/commit/111a571a24eec432f53d600760c68dac0114f73f.

If you’re using pip, make sure to update django-qrauth (I’ve made a new release: _0.1.1_).

Once again, thank you!
